autoencoder: 'DST' 
autoencoder_num_epochs: 50         
hidden_size: 8                     
autoencoder_lr: 0.001                
corr_coeff_param: 0              
context_input: True               # Check to see if we'll add demographic context to the input
autoencoder_saving_period: 10
pol_learning_rate: 0.0001

# DST Hyperparameters
gru_n_layers: 2
augment_chs: 8
decoder_hidden_units: 64