autoencoder: 'AE' # 'Autoencoder'
autoencoder_num_epochs: 400       
hidden_size: 256              
autoencoder_lr: 0.00 
autoencoder_saving_period: 10
corr_coeff_param: 0               
context_input: False 
pol_learning_rate: 0.0001